language: node_js
node_js:
  - lts/*
notifications:
  email:
    on_success: never
    on_failure: always
branches:
  only:
    - master
install:
  - travis_retry npm install

deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
